head:
  js:
    async:
      # è¿™é‡Œæ˜¯ä½ ä» iconfont å¤„è·å¾—çš„å›¾æ ‡é“¾æ¥ã€‚
      iconfont: //at.alicdn.com/t/c/font_3758607_b54o3gjifi6.js


banner:
  enable: true
  title: 1514çš„å°ç«™
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line

menu:
  home:
    path: /
    icon: ri:home-4-line
  list:
    - type: archives
      path: /archives/
      icon: ri:archive-line
    - type: categories
      path: /categories/
      icon: ri:folder-2-line
    - type: tags
      path: /tags/
      icon: ri:price-tag-3-line
  custom:
    title: å‹é“¾
    path: /links/
    icon: ri:settings-line

pages:
  - name:
    url: /guestbook
    icon: ri:women-line
    color: '#ff72b8'

# å¤´åƒ
avatar:
  enable: true
  url: /images/1514.jpg
  rounded: true
  opacity: 1
  mickey_mouse: false
  status:
    enable: true
    emoji: ğŸŒŒ
    message: ä¸æƒ³ä¸Šå­¦

# æ¨¡å¼
mode: time

# éšæœºå¤šè¾¹å½¢èƒŒæ™¯
trianglify:
  enable: false
  cellSize: 75
  width: 800
  height: 600
  palette: '["YlGnBu", "GnBu", "Purples", "Blues"]'
  opacity: 0.5

# çƒŸèŠ±
fireworks:
  enable: true
  colors:
    - '102, 167, 221'
    - '62, 131, 225'
    - '33, 78, 194'

# å›¾ç‰‡æ”¾å¤§é¢„è§ˆ
medium_zoom: true

# å…‰æ ‡
cursor:
  enable: true
  default: https://cdn.yunyoujun.cn/css/md-cursors/pointer.cur
  pointer: https://cdn.yunyoujun.cn/css/md-cursors/link.cur
  text: https://cdn.yunyoujun.cn/css/md-cursors/text.cur

# ç›®å½•
toc:
  list_number: true
  max_depth: 6
  min_depth: 1
  placeholder: å¾ˆé—æ†¾ï¼Œè¿™ç¯‡æ–‡ç« æ²¡æœ‰ç›®å½•å“¦
  collapse: false

widget_tree:
  cdn: true
  hide: false
  layout: tree
  showCount: true
  toc:
    enable: true
    list_number: false

# æ‰“èµ
reward:
  enable: false
  icon: ri:hand-coin-line
  comment: I'm so cute.
  # url: https://github.com/YunYouJun/yunyoujun.github.io/issues/96
  methods:
    - name: æ”¯ä»˜å®
      path: https://cdn.yunyoujun.cn/img/donate/alipay-qrcode.jpg
      color: '#00A3EE'
      icon: ri:alipay-line
      # link: https://xxxx
    - name: QQ æ”¯ä»˜
      path: https://cdn.yunyoujun.cn/img/donate/qqpay-qrcode.png
      color: '#12B7F5'
      icon: ri:qq-line
    - name: å¾®ä¿¡æ”¯ä»˜
      path: https://cdn.yunyoujun.cn/img/donate/wechatpay-qrcode.jpg
      color: '#2DC100'
      icon: ri:wechat-pay-line



# ä¸€é”®èµ‹å€¼
codeblock:
  copy_btn: true

# markdown
mermaid:
  enable: true
  options: https://github.com/knsv/mermaid/blob/master/src/mermaidAPI.js
  startOnload: true
  global: true
  

# è®¡æ•°
wordcount:
  enable: true
  count: true
  time: true

# æ ‡ç­¾äº‘
wordcloud:
  enable: true
  height: 350


# æ–‡ç« å¡ç‰‡é€æ˜åº¦
post_card:
  opacity: 0.3

footer:
  since: 2020
  icon:
    name: ri:cloud-line
    animated: true
    color: '#0078E7'
  live_time:
    enable: true
    prefix: æœ¬åšå®¢å·²èŒèŒå“’åœ°è¿è¡Œ
    suffix: (â—'â—¡'â—)
    start_time: '2022-11-02T00:00:00'
  powered:
    enable: false

say:
  enable: true
  api: /data/sentences.json
  hitokoto:
    enable: true
    api: https://v1.hitokoto.cn


social:
  # - name: RSS
  #   # set rss in your root config
  #   # https://github.com/hexojs/hexo-generator-feed
  #   link: /atom.xml # config.feed.path
  #   icon: ri:rss-line
  #   color: orange
  - name: GitHub
    link: https://github.com/guLinga
    icon: ri:github-line
    color: '#181717'
  - name: æ˜é‡‘
    link: https://juejin.cn/user/3316588148427885/posts
    icon: icon-juejin
  - name: CSDN
    link: https://blog.csdn.net/qq_51965698
    icon: icon-csdn
    color: '#fc5531'
  - name: BFE.dev
    link: https://bigfrontend.dev/user/ptACGZQ
    icon: icon-dev
    color: '#ff1a00'
  - name: E-Mail
    link: mailto:xsx1514@163.com
    icon: ri:mail-line
    color: '#8E71C1'
  - name: å“”å“©å“”å“©åŠ¨ç”»
    link: https://space.bilibili.com/179654060
    icon: ri:bilibili-line
    color: '#FF8EB3'

notice:
  enable: true
  content: æ¬¢è¿æ¥åˆ°æˆ‘çš„å°ç«™.

tags:
  Vue: '#4fc08d'
  Hexo: '#0E834D'
  CSS: '#5298d1'
  Node.js: '#026E00'
  Git: '#F14E32'
  React: '#61dafb'
  Python: '#3776ab'
  PHP: '#8892BF'
  VS Code: '#0066B8'
  JavaScript: '#F4DF4F'
  TypeScript: '#317AC6'
  Laravel: '#F4645F'

# ç½‘ç«™è®¡æ•°å™¨
busuanzi:
  enable: false
  site_uv: true
  site_uv_icon: ri:user-line
  site_pv: true
  site_pv_icon: ri:eye-line
  page_pv: true
  page_pv_icon: ri:eye-line


# è¯„è®º
comment:
  enable: true
  tips:
  candidates:
    # - github_discussions
    # - giscus

# github DiscussionsæœåŠ¡
# github_discussions:
#   enable: true
#   username: guLinga
#   repository: guLinga.github.io

giscus:
  enable: true
  repo: guLinga/guLinga.github.io
  repo-id: R_kgDOIW5gZA
  category: General
  category-id: DIC_kwDOIW5gZM4CSWdD
  mapping: pathname
  reactions-enabled: 1
  emit-metadata: 0
  theme: light

# valine:
#   enable: true
#   appid: HQPbfjfsTamyPNCc94aLkERT-gzGzoHsz
#   appkey: zwoqIXJL2HWoUzmfzA0r3oqa
#   notify: true
#   verify: true
#   placeholder: \(@^0^@)/
#   avater: mm
#   guest_info: nick,mail,link
#   pageSize: 10
#   visitor: false
#   comment_count: true

# é»˜å“€
mourn:
  enable: true
  days:
    - 4-4
